export const SET_ALERT = 'SET_ALERT';
export const CANCEL_ALERT = 'CANCEL_ALERT';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const DISPLAY_PROFILE_PANEL = 'DISPLAY_PROFILE_PANEL';
export const DISPLAY_PROFILE_FOLLOWERS = 'DISPLAY_PROFILE_FOLLOWERS';
export const DISPLAY_PROFILE_FOLLOWING = 'DISPLAY_PROFILE_FOLLOWING';
export const DISPLAY_PROFILE_EDITINFO = 'DISPLAY_PROFILE_EDITINFO';
export const DISPLAY_PROFILE_EDITPASSWORD = 'DISPLAY_PROFILE_EDITPASSWORD';
export const DISPLAY_PROFILE_DELETEACCOUNT = 'DISPLAY_PROFILE_DELETEACCOUNT';

export const DISPLAY_USER_COMMENTED = 'DISPLAY_USER_COMMENTED';
export const DISPLAY_USER_LIKED = 'DISPLAY_USER_LIKED';
export const DISPLAY_USER_SHARED = 'DISPLAY_USER_SHARED';
